myblog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

myblog/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('recipes/', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.recipes_list, name='recipes_list'),
    path('recipe/<int:pk>', views.recipe_detail, name='recipe_detail'),
]

myblog/blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

myblog/recipes/models.py
from django.db import models


class Category(models.Model):

    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    ingredients = models.TextField()
    text = models.TextField()
    image = models.ImageField(upload_to='images/')
    category = models.ManyToManyField(Category)
    easy = models.BooleanField(default=False)

    def __str__(self):
        return self.title

myblog/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

myblog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts' : posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

myblog/recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Recipe, Category

#def recipes_list(request):
#    recipes = Recipe.objects.order_by('author').reverse()
#    categories = Category.objects.order_by('name')
#    return render(request, 'recipes/recipes_list.html', {'recipes': recipes, 'categories': categories})

def recipe_detail(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    return render(request, 'recipes/recipe_detail.html', {'recipe': recipe})

def recipes_list(request):
    id = 0
    categories = Category.objects.all()
    recipes = Recipe.objects.order_by('author').reverse()
    
    if request.method == "POST":
        if '7' in request.POST:
            return render(request, 'recipes/recipes_list.html', {'recipes': recipes, 'categories': categories})
        
        else:
            for cat in categories:
                id += 1
                check = str(id)
                if check in request.POST:
                    break
            recipes = Recipe.objects.filter(category=id)
            return render(request, 'recipes/recipes_list.html', {'recipes': recipes, 'categories': categories})
    
    else:
        return render(request, 'recipes/recipes_list.html', {'recipes': recipes, 'categories': categories})

myblog/blog/templates/blog/base.html
{% load static %}

<html>
    <head>
        <title>Django blog</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span>+</span></a>
            {% endif %}
            <h1><a href="/blog/">Django Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

myblog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}

        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

myblog/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

myblog/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

myblog/recipes/templates/recipes/base.html
{% load static %}

<html lang="pl">
    <head>
        <title>Recipes</title>
        <link rel="stylesheet" href="{% static 'css/recipes.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="wrapper">
            <header>
                <section class="menu-background">
                    <nav class="menu">
                        <a class="logo" href="{% url 'recipes:recipes_list' %}">Recipes Logo</a>
                        <a href="{% url 'recipes:recipes_list' %}">Recipes</a>
                        <a href="{% url 'blog:post_list' %}">Blog</a>
                        <a href="">O mnie</a></li>
                        <input type="text" placeholder="Search.." class="search">
                    </nav>
                </section>
            </header>
                {% block content %}
                {% endblock %}
            <footer>
                <div class="foot">
                    <div class="image"><img width="150px" height="200px" src="/media/images/fomo.jpeg" alt=""></div>
                    <div class="contact">
                        <a class="logo" href="{% url 'recipes:recipes_list' %}">Recipes Logo</a>
                        <p>Tomasz Steckiewicz</p>
                        <p>tomsteckiewicz@gmail.com</p>
                    </div>
                </div>
            </footer>
        </div>
    </body>
</html>

myblog/recipes/templates/recipes/recipe_detail.html
{% extends 'recipes/base.html' %}

{% block content %}
        <section class="recipes-detail">
        <div class="details">
                
                <div class="detail">
                        <h1>{{ recipe.title }}</h1>
                </div>
                <div class="ingredients">
                        <h2>Ingredients</h2>
                    <p>{{ recipe.ingredients|linebreaksbr }}</p>
                </div>
                <div class="preparation">
                        <h2>Preparation</h2>
                    <p>{{ recipe.text }}</p>
                </div>
                <div class="image">
                        <img width="280px" height="280px"src={{ recipe.image.url }} alt={{ recipe.title }}>
                </div>
        </div>
        </section>
{% endblock %}

myblog/recipes/templates/recipes/recipes_list.html
{% extends 'recipes/base.html' %}

{% block content %}

<section class="categories-background">
    <nav class="categories">
        {% for cat in categories %}
        <!-- <form action="POST" method="POST">
            <div class="button-container">
                <span class="button">
                    <input class="input" type="checkbox" {% if cat.name == 'All' %} checked="checked" {% endif %} id="{{ cat }}" name="cat">
                    <label for="{{ cat }}">{{ cat }}</label>
                </span>
            </div>
        </form> -->
        <div class="button-container">
            <form method="POST">{% csrf_token %}
                <button name="{{ cat.pk }}" class="button">{{ cat }}</button>
            </form>
        </div>
        {% endfor %}
    </nav>
</section>
<section class="list-background">
        <nav class="recipes-list">
            {% for recipe in recipes %}
                <div class="recipe">
                    <a href="{% url 'recipes:recipe_detail' pk=recipe.pk %}">
                        <img width="280px" height="280px"src={{ recipe.image.url }} alt={{ recipe.title }}>
                    </a>
                    <a href="{% url 'recipes:recipe_detail' pk=recipe.pk %}">{{ recipe.title }}</a>
                </div>
            {% endfor %}
            </nav>
</section>
{% endblock %}